grocery = []
print(grocery)
grocery.append('bread')
grocery.append('eggs')
print(grocery[0])
print(grocery[0].title())
print(grocery[-1])
print(f"The first element in the list is {grocery[0].title()}")
grocery[0] = 'butter'
print(grocery)
grocery.append('bread')
print(grocery)
grocery.insert(0, 'yoghurt')
print(grocery)
del grocery[1]
print(grocery)
pop_grocery = grocery.pop()
print(pop_grocery)
print(grocery)
pop_grocery = grocery.pop(0)
print(grocery)
grocery.remove('eggs')
print(grocery)
grocery.append('bread')
print(grocery)
remove_grocery = 'bread'
grocery.remove(remove_grocery)
print(grocery)
grocery.append('bread')
grocery.append('eggs')
grocery.insert(0, 'yoghurt')
grocery.sort()
print(grocery)
grocery.sort(reverse=True)
print(grocery)
print(sorted(grocery))
print(len(grocery))
grocery.reverse()
print(grocery)
print(sorted(grocery, reverse=True))